"""add_approver_id_to_reports

Revision ID: 3caa8d2db7c6
Revises: 
Create Date: 2026-06-11 20:12:22.678748
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3caa8d2db7c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('approver_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reports', 'users', ['approver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'approver_id')
    # ### end Alembic commands ###
